### ISSUE TITLE
NugetPackage 관련 설정 이슈

### ISSUE THREAD

**Issue by devncore-james** [devncore/devncore#5]
NugetPackage와 GitHub 소스코드 연결이 필요합니다.
- [ ] 종속성 연결
- [ ] 하나의 레포지토리에서 여러 패키지 설정

[GitHub NugetPackage 연결 가이드](https://musma.github.io/2020/12/17/github-package-registry-nuget.html)
[GitHub 공식 가이드](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry)

**Comment by devncore-elena** [comment]
참고 URL: https://steveellwoodnlc.medium.com/error-nu5026-the-file-to-be-packed-was-not-found-on-disk-18bfbc6be4a
